In [31]:
# Import all necessary libraries.
import pandas as pd
import numpy as np
from sklearn.naive_bayes import BernoulliNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, roc_curve, auc
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.naive_bayes import MultinomialNB

In [32]:
x_train = np.array(['Chinese Beijing Chinese',
'Chinese Chinese Shanghai',
'Chinese Macao',
'Tokyo Japan Chinese'])

x_test = np.array(['Chinese Chinese Chinese Tokyo Japan'])

y_train = np.array(['china','china','china','not china'])


# Bernoulli

In [33]:
# Instantiate a CountVectorizer object.
vect = CountVectorizer(binary=True)

In [34]:
# Fit and transform X_train into x_train_dtm (document-term matrices - dtm).
x_train_dtm = vect.fit_transform(x_train)

In [35]:
# Transform X_test into X_test_dtm.
x_test_dtm = vect.transform(x_test)

In [36]:
# Instantiate a Bernoulli Naive Bayes model.
model = BernoulliNB(binarize=None)

In [37]:
# train the model using X_train_dtm
model.fit(x_train_dtm, y_train)

BernoulliNB(alpha=1.0, binarize=None, class_prior=None, fit_prior=True)

In [38]:
y_pred_class = model.predict(x_test_dtm)

print(ypb)

['not china']


In [39]:
print(vect.get_feature_names())
print(x_train_dtm.toarray())

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']
[[1 1 0 0 0 0]
 [0 1 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]


In [40]:
print(x_test_dtm.toarray())
print(model.predict_proba(x_test_dtm))

[[0 1 1 0 0 1]]
[[0.19106679 0.80893321]]


# Multinomial

In [41]:
vect = CountVectorizer()

x_train_dtm = vect.fit_transform(x_train)

print(vect.get_feature_names())
print(x_train_dtm.toarray())

['beijing', 'chinese', 'japan', 'macao', 'shanghai', 'tokyo']
[[1 2 0 0 0 0]
 [0 2 0 0 1 0]
 [0 1 0 1 0 0]
 [0 1 1 0 0 1]]


In [42]:
# Instantiate a Multinomial Naive Bayes model.
mtn = MultinomialNB()

In [43]:
# train the model using X_train_dtm
mtn.fit(x_train_dtm, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [44]:
x_test_dtm = vect.transform(x_test)

ypm = mtn.predict(x_test_dtm)

print(ypm)

['china']


In [45]:
print(x_test_dtm.toarray())
print(mtn.predict_proba(x_test_dtm))

[[0 3 1 0 0 1]]
[[0.68975861 0.31024139]]
